# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"H\n\x10\x43heckUserRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"#\n\x11\x43heckUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32\x41\n\x0bUserManager\x12\x32\n\tCheckUser\x12\x11.CheckUserRequest\x1a\x12.CheckUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKUSERREQUEST']._serialized_start=14
  _globals['_CHECKUSERREQUEST']._serialized_end=86
  _globals['_CHECKUSERRESPONSE']._serialized_start=88
  _globals['_CHECKUSERRESPONSE']._serialized_end=123
  _globals['_USERMANAGER']._serialized_start=125
  _globals['_USERMANAGER']._serialized_end=190
# @@protoc_insertion_point(module_scope)
